name: Update Scholar Papers

on:
  schedule:
    - cron: '0 0 * * 0'   # ogni domenica a mezzanotte
  workflow_dispatch:       # avvio manuale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run update script
        run: python update.py

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add index.html
          git commit -m "Aggiornamento automatico paper da Scholar" || echo "Nessuna modifica"
          git push
